# Generated by Django 4.0.4 on 2022-07-11 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('deleted', models.CharField(choices=[('0', 0), ('1', 1)], max_length=2)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(max_length=50)),
                ('deleted_by', models.CharField(max_length=50)),
                ('updated_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(max_length=50)),
                ('deleted_by', models.CharField(max_length=50)),
                ('updated_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('deleted', models.CharField(choices=[('0', 0), ('1', 1)], max_length=2)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(max_length=50)),
                ('deleted_by', models.CharField(max_length=50)),
                ('updated_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_manager_app.employee')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_manager_app.sector')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_manager_app.employee')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_manager_app.sector')),
            ],
        ),
    ]
