# Generated by Django 4.0.1 on 2023-07-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='active',
            field=models.CharField(choices=[('Yes', True), ('No', False)], default=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='role',
            name='active',
            field=models.CharField(choices=[('Yes', True), ('No', False)], default=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='sector',
            name='active',
            field=models.CharField(choices=[('Yes', True), ('No', False)], default=True, max_length=5),
        ),
    ]
