# Generated by Django 4.0.4 on 2022-07-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='deleted',
            field=models.CharField(choices=[('0', 0), ('1', 1)], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='employee',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='deleted',
            field=models.CharField(blank=True, choices=[('0', 0), ('1', 1)], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
