# Generated by Django 4.0.4 on 2022-07-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.RemoveField(
            model_name='role',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='status',
        ),
        migrations.AddField(
            model_name='employee',
            name='active',
            field=models.CharField(choices=[('Yes', True), ('No', False)], default=True, max_length=5),
        ),
        migrations.AddField(
            model_name='role',
            name='active',
            field=models.CharField(choices=[('Yes', True), ('No', False)], default=True, max_length=5),
        ),
        migrations.AddField(
            model_name='sector',
            name='active',
            field=models.CharField(choices=[('Yes', True), ('No', False)], default=True, max_length=5),
        ),
    ]
