# Generated by Django 4.0.4 on 2022-07-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager_app', '0003_alter_employee_deleted_alter_sector_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
