# Generated by Django 4.0.4 on 2022-07-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager_app', '0004_alter_employee_created_date_alter_role_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='deleted',
            field=models.CharField(choices=[('1', 1), ('0', 0)], default='0', max_length=2),
        ),
    ]
