# Generated by Django 4.0.4 on 2022-07-20 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager_app', '0006_role_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account_manager_app.role'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='deleted',
            field=models.CharField(choices=[('0', 0), ('1', 1)], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='role',
            name='deleted',
            field=models.CharField(choices=[('0', 0), ('1', 1)], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='sector',
            name='deleted',
            field=models.CharField(choices=[('0', 0), ('1', 1)], default='0', max_length=2),
        ),
    ]
